require: rubocop-performance

# overrides
Style/Documentation:
  Enabled: false
Style/MutableConstant:
  EnforcedStyle: strict
Style/StringLiterals:
  EnforcedStyle: double_quotes

# opt-in new cops
AllCops:
  NewCops: enable
