require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

  # opt-in new cops
  NewCops: enable

# overrides
Style/Documentation:
  Enabled: false
Style/MutableConstant:
  EnforcedStyle: strict
Style/StringLiterals:
  EnforcedStyle: double_quotes
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
