name: CI

on:
  pull_request:
  push:
    branches:
    - main

# TODO: actions/cache to speed up deployment
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Install dependencies
      run: bundle install --jobs 20 --retry 5
    - name: Lint files
      run: bundle exec rubocop
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Install dependencies
      run: bundle install --jobs 20 --retry 5
    - name: Run tests
      run: bundle exec rspec
