name: CI

on:
  pull_request:
  push:
    branches:
    - main

# TODO: actions/cache to speed up deployment
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@master
      with:
        ruby-version: 2.6.6
    - name: Install dependencies
      run: bundle install --jobs 20 --retry 5
    - name: Lint files
      run: bundle exec rubocop
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6.6
    - name: Install dependencies
      run: bundle install --jobs 20 --retry 5
    - name: Run tests
      run: bundle exec rspec
